secondTask
Rikucode/DocInfo pull request #3
Opened 2022-10-15 16:22 UTC by Rikucode

2022-10-15 22:51 UTC, Vixorem requested changes

2022-10-15 22:51 UTC, Vixorem commented on DomainLogic/Doctor.cs
> +    public class Doctor
Разве это не должны было быть в первом задании?

2022-10-15 22:51 UTC, Vixorem commented on DomainLogic.Tests/UnitTest.cs
> +            var result =
Оно ведь даже не сбилдится

2022-10-16 03:09 UTC, Rikucode commented on DomainLogic/Doctor.cs
> +    public class Doctor
а я не знаю почему оно еще раз залилось...

2022-10-16 21:02 UTC, Vixorem approved these changes

2022-10-16 21:02 UTC, Vixorem commented on DomainLogic/User.cs
> +        enum Role
Роль отдельно в файл

2022-10-18 05:21 UTC, merged