ThirdTask
Rikucode/DocInfo pull request #4
Opened 2022-10-18 16:22 UTC by Rikucode

2022-10-18 21:40 UTC, Vixorem commented
Где еще один ревьювер

2022-10-19 09:53 UTC, Rikucode commented
> Где еще один ревьювер

Добавил)

2022-10-21 10:37 UTC, Kim-Inyo commented
Всё хорошо

2022-10-21 10:44 UTC, Kim-Inyo approved these changes

2022-10-22 13:15 UTC, Vixorem requested changes

2022-10-22 13:15 UTC, Vixorem commented on DomainLogic/Contexts/AppointmentContext.cs
> +    public class AppointmentContext : DbContext
А вот эти все контексты они зачем

2022-10-22 13:15 UTC, Vixorem commented on DomainLogic/Services/AppointmentService.cs
> +        public Result<IEnumerable<DateOnly>> GetFreeDates(Speciality speciality)
Мне кажется время тоже нужно

2022-10-22 13:15 UTC, Vixorem commented on DomainLogic/Services/AppointmentService.cs
> +        public Result<Appointment> AddAppointment(Doctor doctor, DateOnly date)
А еслм на эту дату уже были апойнтменты у доктора

2022-10-22 13:15 UTC, Vixorem commented on DomainLogic/Services/DoctorService.cs
> +                var result = _doctorRepository.DeleteDoctor(doctor);
А если у врача есть приемы, мож тогда не удалять

2022-10-22 13:21 UTC, Rikucode commented on DomainLogic/Contexts/AppointmentContext.cs
> +    public class AppointmentContext : DbContext
Для того чтобы данные в будущем считывать?

2022-10-22 17:49 UTC, Rikucode commented on DomainLogic/Services/DoctorService.cs
> +                var result = _doctorRepository.DeleteDoctor(doctor);
исправил

2022-10-22 17:49 UTC, Rikucode commented on DomainLogic/Services/AppointmentService.cs
> +        public Result<Appointment> AddAppointment(Doctor doctor, DateOnly date)
исправил

2022-10-22 17:49 UTC, Rikucode commented on DomainLogic/Services/AppointmentService.cs
> +        public Result<IEnumerable<DateOnly>> GetFreeDates(Speciality speciality)
исправил

2022-10-23 07:44 UTC, Vixorem commented on DomainLogic/Contexts/AppointmentContext.cs
> +    public class AppointmentContext : DbContext
Ну смотри
- В задании этого не было
- Это бессмысленный код, потому что он никогда не вызывается
- Этот код тупо не работает, потому что тут не указана база данных

Нет смысла заранее писать то, что пока что не нужно

2022-10-23 07:44 UTC, Vixorem approved these changes

2022-10-23 11:59 UTC, closed without merging