Fourth task
Rikucode/DocInfo pull request #5
Opened 2022-11-16 16:41 UTC by Rikucode

Доброго времени суток, делаю пул реквест с нерабочим проектом, т.к вроде бы все написал, но оно не работает (сделал тест с добавлением данных, но ничего не происходит). Думаю, здесь будет легче с этим разобраться, так что как-то так.
Буду рад любой помощи

2022-11-16 23:20 UTC, Vixorem requested changes

2022-11-16 23:20 UTC, Vixorem commented on Contexts/AppointmentContextFactory.cs
> +                "Data Source=Database.db");
А тут точно не нужно еще доп инфу типа пароля юзера и тд

2022-11-16 23:20 UTC, Vixorem commented on Contexts/DoctorContext.cs
> +    public class DoctorContext : DbContext
А зачем отдельно доктор контекс и прочие. Это все в одном общем контексте должно быть. Просто в этом контексте разные DbSetы

2022-11-18 15:58 UTC, Rikucode commented
Ну, я вроде исправил недочеты, но я не понимаю почему данные в БД не заносятся(

2022-11-19 00:01 UTC, Vixorem commented
> Ну, я вроде исправил недочеты, но я не понимаю почему данные в БД не заносятся(

Кажется у меня есть идея. Ты вроде бы не вызываешь context.SaveChanges()

2022-11-19 02:45 UTC, Rikucode commented
> > Ну, я вроде исправил недочеты, но я не понимаю почему данные в БД не заносятся(
> 
> Кажется у меня есть идея. Ты вроде бы не вызываешь context.SaveChanges()

```
public void InsertTest()
        {
            UserModel userModel = new UserModel();
            userModel.id = 1;
            userModel.name = "Артём";
            userModel.login = "Rikugou";
            userModel.phone_number = "88005553535";
            _context.Users.Add(userModel);
            _context.SaveChanges();
        }
```
У меня такой тест есть, вызываю в UserTests:
```
public void Insert()
        {
            _userRepository.InsertTest();
            Assert.True(true);
        }
```

2022-11-19 03:42 UTC, Vixorem commented
Хм. А ты смотрел в дебаге? Во время дебага, если идти стоку за строкой, в какой нибудь момент случаем не вылетает эксепшн?

2022-11-19 03:55 UTC, Vixorem approved these changes

2022-11-19 03:55 UTC, Vixorem commented on DomainLogic/Doctor.cs
> +        public int speciality_id;
Тут тоже сделать автосвойство

2022-11-19 03:55 UTC, Vixorem commented on Repositories/AppointmentRepository.cs
> +        public virtual void Dispose(bool disposing)
Это типа диспоус паттерн? Откуда такая идея?)

2022-11-20 06:47 UTC, Vixorem approved these changes

2022-11-20 06:49 UTC, merged